module.exports = {
  purge: [
    './src/components/**/*.{js,ts,jsx,tsx}',
    './src/pages/**/*.{js,ts,jsx,tsx}',
  ],
  prefix: '',
  important: false,
  separator: ':',
  darkMode: 'media',
  theme: {
    extend: {
      transformOrigin: {
        0: '0%',
      },
      zIndex: {
        '-1': '-1',
      },
      colors: {
        transparent: 'transparent',
        black: '#000',
        white: '#fff',
        background: {
          100: '#fff',
        },
        primary: {
          100: '#D1DAFC',
          200: '#A4B4F9',
          300: '#748AEF',
          400: '#5067DF',
          500: '#1E37CB',
          600: '#1529AE',
          700: '#0F1E92',
          800: '#091475',
          900: '#050D61',
        },
        secondary: {
          100: '#E1FDF6',
          200: '#C3FBF3',
          300: '#A2F3EE',
          400: '#87E6E8',
          500: '#61CDD9',
          600: '#46A5BA',
          700: '#30809C',
          800: '#1E5D7D',
          900: '#124368',
        },
        purple: {
          100: '#FADEF4',
          200: '#F5BFEE',
          300: '#E197DE',
          400: '#C173C4',
          500: '#94479e',
          600: '#773387',
          700: '#5C2371',
          800: '#43165B',
          900: '#300D4B',
        },
        pink: {
          100: '#FDDDE0',
          200: '#FCBDC7',
          300: '#F79AB3',
          400: '#F07FA8',
          500: '#e65699',
          600: '#C53E8B',
          700: '#A52B7C',
          800: '#851B6C',
          900: '#6E1061',
        },
        yellow: {
          100: '#FEF6CB',
          200: '#FEEC98',
          300: '#FCDD64',
          400: '#F9CE3E',
          500: '#F6B700',
          600: '#D39700',
          700: '#B17A00',
          800: '#8E5E00',
          900: '#764B00',
        },
        success: {
          100: '#E9FEE1',
          200: '#CEFDC3',
          300: '#ADFAA4',
          400: '#8DF58C',
          500: '#67EF72',
          600: '#4BCD61',
          700: '#33AC53',
          800: '#208A46',
          900: '#13723D',
        },
        warning: {
          100: '#FEF2D0',
          200: '#FDE2A1',
          300: '#FBCD72',
          400: '#F8B84E',
          500: '#F49716',
          600: '#D17810',
          700: '#AF5C0B',
          800: '#8D4407',
          900: '#753204',
        },
        danger: {
          100: '#FCE7DE',
          200: '#FACBBF',
          300: '#F1A59B',
          400: '#E3817F',
          500: '#D2565E',
          600: '#B43E51',
          700: '#972B45',
          800: '#791B3A',
          900: '#641034',
        },
        silver: {
          100: '#EFF8FC',
          200: '#DFEFF9',
          300: '#C9DFEE',
          400: '#637993',
          500: '#2B384B',
          600: '#1F2B40',
          700: '#152036',
          800: '#0D162B',
          900: '#080E24',
        },
      },
    },
    fontFamily: {
      nunito: ['Nunito', 'Arial', 'sans-serif'],
      montserrat: ['Montserrat', 'Arial', 'sans-serif'],
    },
  },
  variants: {
    accessibility: ['responsive', 'focus'],
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    appearance: ['responsive'],
    backgroundAttachment: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus', 'group-hover'],
    backgroundPosition: ['responsive'],
    backgroundRepeat: ['responsive'],
    backgroundSize: ['responsive'],
    borderCollapse: ['responsive'],
    borderColor: ['responsive', 'hover', 'focus', 'focus-within'],
    borderRadius: ['responsive'],
    borderStyle: ['responsive'],
    borderWidth: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    boxSizing: ['responsive'],
    cursor: ['responsive'],
    display: ['responsive'],
    fill: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    float: ['responsive'],
    clear: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontSmoothing: ['responsive'],
    fontStyle: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    inset: ['responsive'],
    justifyContent: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    objectFit: ['responsive'],
    objectPosition: ['responsive'],
    opacity: ['responsive', 'hover', 'focus'],
    order: ['responsive'],
    outline: ['responsive', 'focus'],
    overflow: ['responsive'],
    padding: ['responsive'],
    placeholderColor: ['responsive', 'focus'],
    pointerEvents: ['responsive'],
    position: ['responsive'],
    resize: ['responsive'],
    stroke: ['responsive'],
    strokeWidth: ['responsive'],
    tableLayout: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus', 'group-hover'],
    textDecoration: ['responsive', 'hover', 'focus'],
    textTransform: ['responsive'],
    userSelect: ['responsive'],
    verticalAlign: ['responsive'],
    visibility: ['responsive'],
    whitespace: ['responsive'],
    width: ['responsive'],
    wordBreak: ['responsive'],
    zIndex: ['responsive'],
    gap: ['responsive'],
    gridAutoFlow: ['responsive'],
    gridTemplateColumns: ['responsive'],
    gridColumn: ['responsive'],
    gridColumnStart: ['responsive'],
    gridColumnEnd: ['responsive'],
    gridTemplateRows: ['responsive'],
    gridRow: ['responsive'],
    gridRowStart: ['responsive'],
    gridRowEnd: ['responsive'],
    transform: ['responsive'],
    transformOrigin: ['responsive'],
    scale: ['responsive', 'hover', 'focus'],
    rotate: ['responsive', 'hover', 'focus'],
    translate: ['responsive', 'hover', 'focus'],
    skew: ['responsive', 'hover', 'focus'],
    transitionProperty: ['responsive'],
    transitionTimingFunction: ['responsive'],
    transitionDuration: ['responsive'],
  },
  corePlugins: {},
  plugins: [require('@tailwindcss/custom-forms')],
};
